[package]
name = "bbqr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# error handling
thiserror = "1.0.59"

# static compile time hashmap
phf = "0.11.0"

# utils
once_cell = "1.19.0"

# faster hashmap/set
ahash = "0.8.0"

